spring:

  application:
    name: clinica.app

  profiles:
    active: "local"

  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: false

  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration