spring:

  datasource:
    url: jdbc:mysql://localhost:3306/clinic
    username: user
    password: admin

  flyway:
    schemas: clinic

  jpa:
    hibernate:
      format_sql: true

logging:
  level:
    org.flywaydb: DEBUG