package br.com.fiap.techchallenge.apiagendamentoconsultas.model;

public enum Especialidade {
    ACUMPUTURA,
    ALERGOLOGIA,
    ANESTESILOGIA,
    ANGILOGIA,
    CARDIOLOGIA,
    CIRURGIA,
    CLINICA,
    COLOPROCTOLOGIA,
    DERMATOLOGIA,
    ENDROCNOLOGIA,
    ENDOSCOPIA,
    GASTROENTEROLOGIA,
    GENETICA,
    GERIATRIA,
    GINECOLOGIA,
    HEMATOLOGIA,
    HOMEOPATIA,
    INFECTOLOGIA,
    MASTOLOGIA,
    NEFROLOGIA,
    NEUROLOGIA,
    PSIQUIATRIA
}
